### ISSUE TITLE
use cases for integer intervals

### ISSUE THREAD

**Issue by swn1** [intiocean/pyinter#21]
I'm just beginning to use this in an application and it's integers I'm interested in.

So far I'm standardizing on a helper function lambda i: pyinter.closedopen(i,i+1)

Next I'm planning to implement an iterator of iterators, where each interval in an IntervalSet is mapped to a standard range object and the whole mess is iterated to enumerate, in order, the integers in the set.

Assuming this works reasonably well I'll hack it into the code and docs and add a pull request.  If you have a better suggestion I'm all ears.

**Comment by intiocean** [comment]
Hey @swn1, I'm so confused! Could you explain what you're trying to achieve? :)

**Comment by swn1** [comment]
Sure ... I'm building a distributed search over a set isomorphic with a compact but largeish set of integers.  At the strategy module I needed some kind of scoreboard that I can update with reports about individual points and ranges of points, and I need to be able to quickly enumerate spans that have not been completed, by any of a handful of measures of completeness (as reported by the worker tasks).

Basically, I need to track ranges that have been assigned, ranges that have not been assigned, ranges that have been completed -- maybe partially completed, and I need to be able to make new assignments quickly as workers become idle, including re-assigning work that has become stale to recover from worker failures.

Having played with it for a while I arrived at a satisfactory use pattern, but my understanding of best practices in python iterables design is still very limited so I'm not confident it's publication-ready.

Anyway, it's a pattern that people who are looking for an interval set library might be interested in, with use illustrated with a horribly inefficient implementation of Eratosthenes' sieve:

import pyinter
def intint(i):
    return pyinter.closedopen(i,i+1)
def intiter(intset):
    for y in sorted(intset):
        for z in range(y.lower_value,y.upper_value):
            yield z


sieve = pyinter.IntervalSet([pyinter.closedopen(2,100)])
for n in list(intiter(sieve)): # make a copy, changes in loop
    nmults = pyinter.IntervalSet()
    for m in range(2*n,100,n):
        nmults.add(intint(m))
    sieve -= nmults

list(intiter(sieve))

So, it's not really much of a code contribute, just documenting a use pattern.
