### ISSUE TITLE
Extrama <= and >= should equal themselves.

### ISSUE THREAD

**Issue by kevincox** [intiocean/pyinter#9]
Each infinity has one comparison-and-equality operator that returns `False` if the values are equal.  It would be nice if this could be fixed.

Tests that show the issue:
```py
assert NEGATIVE_INFINITY >= NEGATIVE_INFINITY
assert INFINITY <= INFINITY
```

**Comment by intiocean** [comment]
Good spot! A couple of tests & a fix PR would be amazing - otherwise I'll take a look when I get a chance.

**Comment by intiocean** [comment]
All sorted - thanks for your contributions @kevincox!

**Comment by kevincox** [comment]
No problem, thanks for the awesome library.
